/*******************************************************************************
 * Copyright 2015-2018 Capgemini SE.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 ******************************************************************************/
package com.devonfw.devcon.output;

import java.util.List;

import com.devonfw.devcon.common.api.Command;
import com.devonfw.devcon.common.api.CommandModuleInfo;
import com.devonfw.devcon.common.api.data.DevconOption;

/**
 * This defines the component which is responsible for all output generated by the application
 *
 * @author ivanderk
 */
public interface Output {

  void showMessage(String message, String... args);

  void showError(String message, String... args);

  void showGeneralHelp(String header, String usage, List<DevconOption> options, List<CommandModuleInfo> modules);

  void showCommandHelp(Command command);

  void showModuleHelp(CommandModuleInfo module);

  void status(String message, String... args);

  /**
   * @deprecated should be removed. All methods should add newline
   */
  @Deprecated
  void statusInNewLine(String message, String... args);

  void success(String command);

}
